FROM python:3.10 as base
LABEL maintainer="Joseph Smith"
LABEL version="0.1.0"
LABEL description="FastAPI server for Zifo Skills Tracker"

# Install wget for health check
RUN apt-get -y update && apt-get -y install wget

# Configure Poetry
ENV POETRY_VERSION=1.2.2
ENV POETRY_HOME=/opt/poetry
ENV POETRY_VENV=/opt/poetry-venv
ENV POETRY_CACHE_DIR=/opt/.cache

# Create and switch to a new user
RUN useradd --create-home skills-user
WORKDIR /home/skills-user

# Install poetry separated from system interpreter
RUN python3 -m venv $POETRY_VENV \
    && $POETRY_VENV/bin/pip install -U pip setuptools \
    && $POETRY_VENV/bin/pip install poetry==${POETRY_VERSION}

# Add `poetry` to PATH
ENV PATH="${PATH}:${POETRY_VENV}/bin"

# Install dependencies
COPY ./pyproject.toml ./pyproject.toml
RUN poetry install

# Copy source code
COPY ./app ./app
COPY ./tests ./tests

# Run the server
EXPOSE 8080

CMD ["poetry", "run", "hypercorn", "app.main:app", "--reload", "--bind", "0.0.0.0:8080"]
