version: "3.8"
services:
  mongodb:
    extends:
      file: ./docker-compose.prod.yml
      service: mongodb

  python-api:
    extends:
      file: ./docker-compose.prod.yml
      service: python-api
    image: zifo-skills-api
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
    build:
      context: ..
      dockerfile: ./docker/api/Dockerfile

  react-frontend:
    extends:
      file: ./docker-compose.prod.yml
      service: react-frontend
    image: zifo-skills-frontend
    build:
      context: ..
      dockerfile: ./docker/frontend/Dockerfile
