name: Build & Run Docker Image
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  docker:
    timeout-minutes: 20
    runs-on: ubuntu-latest

  steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start containers
      run: docker compose up -d --build;

    - name: Run pipeline
      run: docker compose exec -T python-api python pipeline/src/run_pipeline.py
