name: Run, test & build docker
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  integration-test:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Start containers
        run: docker compose up -d --build;

  build-prod:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Start containers
        run: docker compose up -d --build;
