name: Run, test & build docker
on:
  push:
    branches: '*'
  pull_request:
    branches: [main, master]

jobs:
  build-dev:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::233044492909:role/skills-tracker-dvc
          aws-region: eu-west-2
      - name: Install DVC
        uses: iterative/setup-dvc@v1
      - name: Pull data with DVC
        run: |
          dvc pull --recursive
      - name: Start containers
        run: docker compose -f docker/docker-compose.dev.yml up -d --build;
