# .github/workflows/neo4j-keepalive.yml
name: Keep Neo4j Aura Free Awake

on:
  schedule:
    - cron: '0 12 * * *' # Runs every day at 12:00 UTC

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
    - name: Run keep-alive query
      run: |
        pip install neo4j
        python -c "
from neo4j import GraphDatabase
driver = GraphDatabase.driver('neo4j+s://07c23eb4.databases.neo4j.io', auth=('neo4j', 'yD37XfYk_XEdqyrRrSi-oIzrXS59H4KiL9K5aKQLvS0'))
with driver.session() as session:
    session.run('RETURN 1')
driver.close()
"
