# .github/workflows/neo4j-keepalive.yml
name: Keep Neo4j Aura Free Awake

on:
  schedule:
    - cron: '0 12 * * *' # Runs every day at 12:00 UTC
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: pip install neo4j

    - name: Write keepalive script
      run: |
        echo 'import os' > keepalive.py
        echo 'from neo4j import GraphDatabase' >> keepalive.py
        echo '' >> keepalive.py
        echo 'uri = os.environ["NEO4J_URI"]' >> keepalive.py
        echo 'auth = (os.environ["NEO4J_USER"], os.environ["NEO4J_PASS"])' >> keepalive.py
        echo '' >> keepalive.py
        echo 'driver = GraphDatabase.driver(uri, auth=auth)' >> keepalive.py
        echo 'with driver.session() as session:' >> keepalive.py
        echo '	session.run("RETURN 1")' >> keepalive.py
        echo 'driver.close()' >> keepalive.py

    - name: Run keepalive script
      env:
        NEO4J_URI: ${{ secrets.NEO4J_URI }}
        NEO4J_USER: ${{ secrets.NEO4J_USER }}
        NEO4J_PASS: ${{ secrets.NEO4J_PASS }}
      run: python keepalive.py
